# Generated by Django 4.2.1 on 2023-05-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsApp', '0002_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('en_attente', 'En attente')], max_length=20)),
            ],
        ),
    ]
