# Generated by Django 4.2.1 on 2023-05-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsApp', '0003_tache'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('profile_photo', models.ImageField(upload_to='profile_photos')),
            ],
        ),
    ]
